---
driver:
  name: vagrant

provisioner:
  name: chef_pantry

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[chef-client::default]
    attributes:
